config/routes.rb
Rails.application.routes.draw do
  resources :mypage do
    member do
      get 'top'
    end
  end

  resources :places do
    collection do
      post 'reorder'
    end
  end
  resources :plans do
    collection do
      post 'add'
      post 'add_member'
      post 'datetime'
      get 'modal_restaurant'
    end
    member do
      get 'member'
      get 'confirm'
      get 'pdf'
      get 'finish_mail'
    end
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'top/index'
  resources :blogs
  root 'top#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:Test, :name)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Test %><br>
    <%= f.text_field :Test %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Test</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.Test %></td>
        <td><%= blog.name %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>



１
<div id="googlemaps1" style="width:400px; height:400px"></div>

２
<div id="googlemaps2" style="width:500px; height:400px"></div>

3(鳥取)
<div id="googlemaps3" style="width:600px; height:400px"></div>

4(ドラッグ不可)
<div id="googlemaps4" style="width:600px; height:400px"></div>

5(ホイール不可)
<div id="googlemaps5" style="width:600px; height:400px"></div>

6(東京にマーカー)
<div id="googlemaps6" style="width:600px; height:400px"></div>

7(鳥取市にマーカーを加える)
<div id="googlemaps7" style="width:600px; height:400px"></div>
<button type="button" id = "maps7_markeranime">クリック</button>
<button type="button" id = "maps7_markerdelete">削除</button>
<br>

8(２地点を結ぶ)
<div id="googlemaps8" style="width:600px; height:400px"></div>
<button type="button" id = "maps8_marker_tottori">クリック（鳥取市）</button>
<button type="button" id = "maps8_marker_yonago">クリック（米子市）</button>
<button type="button" id = "maps8_polylines_yonago_to_tottori">クリック（結ぶ）</button><br>

9(入力した住所または地名に移動)
<div id="googlemaps9" style="width:600px; height:400px"></div>
<div id = "point" style= "width:300px; margin-right:auto;"></div>
場所 <input type = "text" id = "address" value = ""><br>
コメント <input type = "text" id = "comment" value = "">
<input type = "button" id = "geo" value = "追加"><br>
<button type="button" id = "polylines_geo">経路作成</button>
<button type="button" id = "polylines_dis">経路作成(道に沿った)</button>
<div id="directions-panel" style="width:600px; height:400px"></div>




<br><br><br><br><br><br><br>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>名前</th>
            <th>特徴</th>
        </tr>
    </thead>
    <tbody id="sortable">
        <tr>
            <th>とんこつラーメン</th>
            <td>コッテリ</td>
        </tr>
        <tr>
            <th>塩ラーメン</th>
            <td>うまい</td>
        </tr>
        <tr>
            <th>醤油ラーメン</th>
            <td>イケてる</td>
        </tr>
        <tr>
            <th>二郎</th>
            <td>関内</td>
        </tr>
    </tbody>
</table>



レストランAPI
レストランAPI
レストランAPI
レストランAPI
レストランAPI
レストランAPI
レストランAPI
レストランAPI
レストランAPI
レストランAPI
レストランAPI
レストランAPI
レストランAPI
レストランAPI
レストランAPI
レストランAPI
レストランAPI
レストランAPI
レストランAPI
レストランAPI
レストランAPI
レストランAPI
レストランAPI
レストランAPI


<!DOCTYPE html>
<html lang="ja" dir="ltr">
<head>
<meta charset="utf-8" />
<title>JSONPでレストラン検索APIの結果を取得するサンプルコード</title>
</head>
<body>
<input type="text" placeholder="enter your access key here" class="js--key"><input type="button" value="apply" class="js--apply" />
<script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>


<script>

(function(){

  var url = 'http://api.gnavi.co.jp/RestSearchAPI/20150630/?callback=?';
  var params = {
    keyid: 'cae5974528b21caa3660751869674b23',
    format: 'json',
    latitude: 35.705518,
    longitude: 139.649267,
    range: 1
  };

  var showResult = function(result){
    if ( result.total_hit_count > 0 ) {
      var res = '';
      alert( result.total_hit_count + '件の結果が見つかりました。\n' );
      for ( var i in result.rest ){
          res += result.rest[i].id + ' ' + result.rest[i].name + ' ' + result.rest[i].url + ' ' + result.rest[i].access.line + ' ' + result.rest[i].access.station + ' ' + result.rest[i].access.walk + '分\n';
      }
      alert(res);
    } else {
      alert( '検索結果が見つかりませんでした。' );
    }
  }

  $(document).on('click', '.js--apply', function(){
  //  params.keyid = $('.js--key').val();
    $.getJSON(url, params, function(result){
      showResult(result);
    });
  });

})(jQuery);

</script>



</body>
</html>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Test:</strong>
  <%= @blog.Test %>
</p>

<p>
  <strong>Name:</strong>
  <%= @blog.name %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>