config/routes.rb
Rails.application.routes.draw do
  resources :mypage do
    member do
      get 'top'
    end
  end

  resources :places do
    collection do
      post 'reorder'
    end
  end
  resources :plans do
    collection do
      post 'add'
      post 'add_member'
      post 'datetime'
      get 'modal_restaurant'
    end
    member do
      get 'member'
      get 'confirm'
      get 'pdf'
      get 'finish_mail'
    end
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'top/index'
  resources :blogs
  root 'top#index'

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :area
  has_many :places
  has_many :plan_users
  has_many :users, through: :plan_users

  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :member, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :member_only, only: [:member, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.where(search_params)
    @areaname = Area.find(search_params[:area_id]).name
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
    @members = @plan.users
    @place = Place.new
    @place.pins.build
    @places = @plan.places.order(:route)

    i = 1
    @hash = Gmaps4rails.build_markers(@places) do |place, marker|
      marker.lat place.latitude
      marker.lng place.longitude
      marker.infowindow "場所：#{place.address}<br>希望者：#{place.user.name}<br>
                        行きたい度：#{place.show_star}<br>コメント：#{place.pins[0].comment}"
      marker.picture({
                :url    => "/#{i}.png",
                #:url    => "https://graph.facebook.com/#{place.user.uid}/picture?width=32&height=32",
                :width  => "28.00000000001",
                :height => "21.00000000001"
               })
      marker.json({title: place.address})
      i = i + 1
    end

    @point = []
    @hash.each do |hash|
      temp= []
      temp.push(hash[:lat])
      temp.push(hash[:lng])
      @point.push(temp)
    end

    if @members.ids.include?(current_user.id)
      render "show"
    else
      render "plan_reference"
    end

  end

  def add
    @place = Place.new(place_params)
    @place.set_route(params[:place][:plan_id])
    respond_to do |format|
      if @place.valid?
        if @place.latitude.nil?
          format.html { redirect_to ({action: 'show', id: @place.plan.id }), alert: '存在する場所を入力してください' }
        else
          @place.save
          format.html { redirect_to ({action: 'show', id: @place.plan.id }), notice: '追加しました' }
          format.json { render :show, status: :created, location: @place }
        end
      else
        #format.html { render :new }
        format.html { redirect_to ({action: 'show', id: @place.plan.id }), alert: '場所が入力されていません' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  def member
    @plan_user = @plan.plan_users.build
    @members = @plan.users
    @joined_members_ids = @plan.users.ids
    @flg = params[:flg]
  end

  def add_member
    @plan_user = PlanUser.new(plan_user_params)
    @plan = @plan_user.plan
    member_only
    respond_to do |format|
      if @plan_user.save
        # deliverメソッドを使って、メールを送信する
        MemberMailer.join_plan_email(plan_user_params[:user_id],plan_user_params[:plan_id],current_user).deliver

        format.html { redirect_to ({action: 'member', id: @plan_user.plan_id }) }
        format.json { render :show, status: :created, location: @plan_user }
      else
        format.html { render :member }
        format.json { render json: @plan_user.errors, status: :unprocessable_entity }
      end
    end
  end

  def datetime
    @place = Place.find(datatime_params[:id])
    #  binding.pry
    respond_to do |format|
      if @place.update(datatime_params)
        format.html { redirect_to plan_path(@place.plan_id), notice: '時間を更新しました' }
        format.json { render :show, status: :ok, location: @plan }
        format.js
      else
        #未完成
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  def confirm
    #binding.pry
    @plan = Plan.find(params[:id])
    @members = @plan.users
    @places = @plan.places.order(:route)
  end

  def pdf
    #binding.pry
    respond_to do |format|
    format.html { redirect_to :action => 'pdf', :format => 'pdf', debug: 1 }
    format.pdf do
      @plan = Plan.find(params[:id])
      @places = @plan.places.order(:route)
      render pdf: 'pdf',
       layout: 'pdf_layout.html.erb',
       encoding: 'UTF-8',
       no_background: false
     end
   end
  end

  def finish_mail
    @plan = Plan.find(params[:id])
    members = @plan.users

    # deliverメソッドを使って、メールを送信する。メンバー全員に送信する
    members.each do |member|
      MemberMailer.plan_finish_email(@plan,member).deliver
    end

    respond_to do |format|
      format.html { redirect_to confirm_plan_path(@plan), notice: '送信しました' }
    end

  end


  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
    @members = @plan.users
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)
    respond_to do |format|
      if @plan.save
        PlanUser.create(plan_id: @plan.id, user_id: current_user.id)
        format.html { redirect_to ({action: 'member', id: @plan.id , flg: 'new'}) }
      # format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: '基本情報を編集しました' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def modal_restaurant
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:name, :start_date, :end_date, :area_id)
    end

    def place_params
      params.require(:place).permit(:user_id, :plan_id, :address, :latitude, :longitude, :route,
                                    pins_attributes: [:comment, :want])
    end

    def plan_user_params
      params.require(:plan_user).permit(:user_id, :plan_id)
    end

    def datatime_params
      params.require(:place).permit(:from, :to, :id)
    end

    def search_params
      params.require(:plan).permit(:area_id)
    end


end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_cushion.html.erb
<%= render partial: 'modal' %>

app/views/plans/_edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

<h1>メンバー編集</h1>
<%= form_for @plan_user, url: add_member_plans_path do |f| %>
  <% if @plan_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan_user.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<br>
追加するメンバーを選択してください。
  <div class="field">
    <%= f.collection_select :user_id, User.where.not(id: @joined_members_ids), :id, :name %>
  </div>
  <div class="field">
    <%= f.hidden_field :plan_id %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-success', value: "メンバーに追加"%>
  </div>
<% end %>

<br>
<h3><現在のメンバー></h3>
  <% @members.each do |member| %>
    <td><%= member.name %></td><br>
    <%= profile_img(member) %>
  <% end %>
  <br>

	<td><%=link_to "決定", plan_path(@plan_user.plan_id), class: 'btn btn-primary', style: "color:white"%></td><br>

</div>
</div>
</div>

app/views/plans/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
        <div class="field input-group">
          <span class="input-group-addon">プラン名</span>
          <%= f.text_field :name %>
        </div>
        <div class="field input-group">
          <span class="input-group-addon">エリア</span>
          <%= f.collection_select :area_id, Area.all, :id, :name %>
        </div>
期間
        <div class="form-inline">
          <div class='input-group date startdatepicker'>
            <%= f.text_field :start_date, class: 'form-control' %>
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
          </div> 〜
          <div class='input-group date enddatepicker'>
            <%= f.text_field :end_date, class: 'form-control' %>
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
          </div>
        </div>
        <br>
        <div class="actions">
          <% if params[:action] == "new" %>
            <%= f.submit class: 'btn btn-primary', value: "次へ", name: "new" %>
          <% else %>
            <%= f.submit class: 'btn btn-primary', value: "決定" %>
          <% end %>
        </div>


<% end %>

    </div>
  </div>
</div>

app/views/plans/_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title">レストラン検索</h4>
    </div>
    <div class="modal-body">検索条件を入力してください
      <p>・エリア</p>
    　<p>・予算</p>
    　<p>・種類</p>

検索範囲
<input type = "radio" name = "range" value = "1">300m
<input type = "radio" name = "range" value = "2">500m
<input type = "radio" name = "range" value = "3" checked>1000m
<input type = "radio" name = "range" value = "4">2000m
<input type = "radio" name = "range" value = "5">3000m


<br>
<input type="button" value="検索" class="js--apply btn btn-primary" />

      <p>検索結果一覧</p>
      <div class = view></div>
    </div>
    <div class="modal-footer">

      <button type="button" class="btn btn-primary" data-dismiss="modal">閉じる</button>
    </div>
  </div>
</div>

app/views/plans/_new.html.erb
	<div class="progress">
		<div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" style="width: 50%;">
			 50%
		</div>
	</div>

<h1>STEP2　続いて参加するメンバーを決めましょう!</h1>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

<%= form_for @plan_user, url: add_member_plans_path do |f| %>
  <% if @plan_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan_user.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<br>
あなたの他にプランに参加するメンバーを選択してください。
  <div class="field">
    <%= f.collection_select :user_id, User.where.not(id: @joined_members_ids), :id, :name %>
  </div>
  <div class="field">
    <%= f.hidden_field :plan_id %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-success', value: "メンバーに追加"%>
  </div>
<% end %>

<br>
<h3><現在のメンバー></h3>
  <% @members.each do |member| %>
    <td><%= member.name %></td><br>
    <%= profile_img(member) %>
  <% end %>
  <br>
	<td><%=link_to "このメンバーでプランを作成する", plan_path(@plan_user.plan_id), class: 'btn btn-primary'%></td><br>
	※ メンバーはあとからでも追加することができます。

    </div>
  </div>
</div>

app/views/plans/datetime.js.erb
//特に処理なし
alert("更新しました");

app/views/plans/edit.html.erb
<h1 class = "text-center">基本情報の編集</h1>

<%= render 'form' %>

app/views/plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>「<%= @areaname %>」の検索結果(<%= @plans.count %>件)</h1>


<div class="container-fluid">
	<div class="row">
		<% @plans.each do |plan| %>
		<div class="col-md-3 col-xs-offset-1">

			<div class="media">
				<a class="media-left" href="#">
					<%= image_tag("/Prefectures/#{plan.area.id}.jpg", :size => "200x200", :alt => "アイコン") %>
				</a>
				<div class="media-rigth">
					<h4 class="media-heading">
						<%=link_to plan.name, plan_path(plan)%>
					</h4>
					メンバー (<%= plan.plan_users.count %>)
				</div>
			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/plans/member.html.erb
<% if @flg == "new" %>
	<%= render :partial => "new" %>
<% else %>
	<%= render :partial => "edit" %>
<% end %>

app/views/plans/modal_restaurant.js.erb
$("#myModal").html("<%= escape_javascript(render 'cushion') %>")
$("#myModal").modal("show")

app/views/plans/new.html.erb
<% if params[:action] == "new" %>
	<div class="progress">
		<div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" style="width: 0%;">
			 0%
		</div>
	</div>
<% end %>


<h3>プランの作成はとっても簡単です。</h3>
<h3>STEP1：　まずはプランの基本情報を入力しましょう</h3>

<%= render 'form' %>

app/views/plans/pdf.pdf.erb
<h1><%= @plan.name %></h1>
<table class = "table">
<thead>
  <tr>
  <th>順番</th>
  <th>場所</th>
  <th>FROM</th>
  <th>TO</th>
  </tr>
</thead>
<tbody>
  <% @places.each do |place| %>
  <tr id="<%= place.id %>">
    <td class = "route"><%= place.route %></td>
    <!--<td><%= place.user.name %></td>-->
    <td><%= place.address %></td>
    <td><%= place.from.strftime("%Y年%m月%d日 %H時%M分") %></td>
    <td><%= place.to.strftime("%Y年%m月%d日 %H時%M分") %></td>
  </tr>
  <% end %>
</tbody>
</table>

app/views/plans/plan_reference.html.erb
これは参照用の画面です。
<div class="container-fluid">
	<div class="row">

		<div class="col-md-5">
      <div style='width: 700px;'>
        <div id="map" style='width: 550px; height: 700px;'></div>
      </div>
    </div>


		<div class="col-md-7">
      <table class = "table">
      <thead>
        <tr>
        <th>順番</th>
        <th>場所</th>
        <th>FROM</th>
        <th>TO</th>
        <tr>
      </thead>
      <tbody>
        <% @places.each do |place| %>
        <tr id="<%= place.id %>">
          <td class = "route"><%= place.route %></td>
          <!--<td><%= place.user.name %></td>-->
          <td><%= place.address %></td>
          <td><%= place.from %></td>
          <td><%= place.to %></td>
        </tr>
        <% end %>
      </tbody>
      </table>
    </div>
	</div>
</div>


<!--ここにdistanceの結果を描画する
<div id="directions-result" style="width:600px; height:1000px"></div>
ここにdistanceの結果を描画する-->




<script type="text/javascript">
poli = [];
point = <%= @point %>;
for (var i = 0; i < point.length; i++) {
  poli.push(new google.maps.LatLng( point[i][0], point[i][1] ));
};

  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(7);
    handler.map.centerOn(poli[0]);

  });

</script>

app/views/plans/show.html.erb
<div class="container-fluid">
	<div class="row">

		<div class="col-md-5">
      <div style='width: 700px;'>
        <div id="map" style='width: 550px; height: 700px;'></div>
      </div>
    </div>


		<div class="col-md-7">
			<!--<h3>場所を追加しましょう！</h3>-->
			<%= form_for @place, url: add_plans_path, method: "post" do |f| %>
				<% if @place.errors.any? %>
					<div id="error_explanation">
						<h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>
						<ul>
						<% @place.errors.full_messages.each do |message| %>
							<li><%= message %></li>
						<% end %>
						</ul>
					</div>
				<% end %>

				<div class="field">
					<%= f.hidden_field :user_id, value: current_user.id  %>
				</div>
				<div class="field">
					<%= f.hidden_field :plan_id, value: @plan.id %>
				</div>
				<div class="field">
					<%= f.hidden_field :latitude %>
				</div>
				<div class="field">
					<%= f.hidden_field :longitude %>
				</div>
				<div class="field">
					<%= f.hidden_field :route %>
				</div>
				<div class="form-inline">
				<div class='input-group'>
					<span class="input-group-addon">場所・住所</span>
	        <%= f.text_field :address, class: 'form-control' %>
				</div>

					<%= f.fields_for :pins do |c| %>
	        <!--  <div class='input-group'>
							<span class="input-group-addon">コメント（任意）</span>
	            <%= c.text_field :comment, class: 'form-control' %>
	          </div> -->
	          <div class='input-group'>
	            <span class="input-group-addon">優先度</span>
								<div class = "form-control">
									<%= c.radio_button :want, 2 %>高
									<%= c.radio_button :want, 1, :checked => "checked" %>中
									<%= c.radio_button :want, 0 %>低
								</div>
	          </div>
					<% end %>
				<div class='input-group'>
				<div class="actions">
					<%= f.submit value: "追加", class: 'btn btn-primary'%>
				</div>
				</div>
			</div>

			<% end %>

		レストラン検索
		<input type="text" placeholder="enter your access key here" class="js--key"><input type="button" value="レストラン検索" class="js--apply" />
		レストラン検索


		<!-- モーダルウィンドウを呼び出すボタン -->
		<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">食事スポットを検索</button>
		<%= link_to 'レストランモーダル', modal_restaurant_plans_path, method: "get", remote: true %>


		<!-- モーダルウィンドウの中身 -->
		<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-hidden="true">
			<!--<%= render partial: 'modal' %>-->
		</div>


      <table class = "table">
      <thead>
        <tr>
        <th>順番</th>
        <th>登録者</th>
        <th>場所</th>
				<th>action</th>
				<th>FROM</th>
				<th>TO</th>
				<th>時間(距離)</th>
        <!-- 緯度・経度は表示しない<th>緯度</th>-->
        <!-- 緯度・経度は表示しない<th>経度</th>-->
        <tr>
      </thead>
      <tbody id="sortable"><%i = 0%>
        <% @places.each do |place| %>
        <tr id="<%= place.id %>">
          <td class = "route"><%= place.route %></td>
          <td><%= place.user.name %></td>
          <td><%= place.address %></td>
          <!-- 緯度・経度は表示しない<td><%= place.latitude %></td>-->
          <!-- 緯度・経度は表示しない<td><%= place.longitude %></td>-->
					<td><%= link_to '削除', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>

				<%= form_for place, url: datetime_plans_path, method: "post", remote: true do |f| %>
					<td><div class='input-group date startdatetimepicker'>
						<%= f.text_field :from, class: 'form-control testid' %>
						<span class="input-group-addon">
					</div></td>
					<td><div class='input-group date enddatetimepicker'>
						<%= f.text_field :to, class: 'form-control testid' %>
						<span class="input-group-addon">
					</div></td>
					<td><div>
						<%= f.hidden_field :id, value: place.id %>
					</div></td>
					<td>
						<!--<div class="actions">
							<%= f.submit class: 'btn btn-primary', value: "更新" %>
						</div>-->
						<div class = "hidden_number">
							<div id ="<%= i%>"></div></div>
					</td>
				<% end %>
        </tr>
        <%i = i + 1%><% end %>
      </tbody>
      </table>
			ドラッグ＆ドロップで経路を変更することで、移動時間/経路が自動で算出されます。<br>
			入力された情報はブラウザを閉じても保存されます。<br><br>
			<!--<button type="button" id = "create_routes" class = 'btn btn-primary'>直線を引く</button>
			<button type="button" id = "create_routes_time" class = 'btn btn-primary'>経路作成</button>-->
			<%= link_to 'この経路で決定', confirm_plan_path(@plan), id: "confirm", class: 'btn btn-primary', style: 'color:white' %>
    </div>
	</div>
</div>

<!--ここにdistanceの結果を描画する
<div id="directions-result" style="width:600px; height:1000px"></div>
ここにdistanceの結果を描画する-->




<script type="text/javascript">
	//alert("ハンドラーの前");
  handler = Gmaps.build('Google');
  defo = new google.maps.LatLng( 39.0686606 , 141.3507552 );
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
		//			alert("実行後");
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(5);
    handler.map.centerOn(defo);
  });

// 場所を線で結ぶメソッド（直線）
	polylines = [];
 	document.getElementById( 'create_routes' ).onclick = function( e ){
   /* 関係ない動作を無効化 */
   var e = e || window.event ;
   e.preventDefault() ;
   e.stopPropagation() ;

 	poli = [];
 	point = <%= @point %>;
 	alert(point.length);
  for (var i = 0; i < point.length; i++) {
		//alert(point[i][1]);
		//alert(point[i][0]);
		//alert(i);
  	poli.push(new google.maps.LatLng( point[i][0], point[i][1] ));
	};

 // var flightPlanCoordinates = [
 // 	new google.maps.LatLng( 35.5, 134.25 ) ,
 //  new google.maps.LatLng( 35.4, 133.31 )
 // ];

// alert("固定");
// alert(flightPlanCoordinates);
		alert("可変");
		alert(poli);
     //1つ目の線(Polyline)のインスタンスを作成する
     //new google.maps.Polyline() ]の引数にオプションオブジェクトを指定する
		 //固定で線を引くことはできる

   polylines[0] = new google.maps.Polyline( {
   	map: handler.getMap() ,
   	path:
			poli,
			strokeColor: '#FF0000' //色（#RRGGBB形式）
   } ) ;
 };


 //場所を線で結ぶ処理（道に沿った線。時間も算出できる）
 rendererOptions = {
 draggable: true,
 preserveViewport: false,
 suppressMarkers: true
 };
 var directionsDisplay =
   new google.maps.DirectionsRenderer(rendererOptions);
 var directionsService =
   new google.maps.DirectionsService();



 var wayPoints = [];
 //経路（道に沿った）や時間を算出する
 document.getElementById( 'create_routes_time' ).onclick = function( e ){
  directionsDisplay.setMap(handler.getMap());
//	alert("始まるよ");
  google.maps.event.addListener(directionsDisplay,
    'directions_changed', function(){
  });
 //経由ポイント@始点と終点を除く
 poli = [];
 point = <%= @point %>;
 //alert(point.length);
	for (var i = 0; i < point.length; i++) {
 //alert(point[i][1]);
 //alert(point[i][0]);
 //alert(i);
	poli.push(new google.maps.LatLng( point[i][0], point[i][1] ));
};
//alert("可変");
		alert(poli);
  for (var i = 1; i < poli.length-1; i++) {
      wayPoints.push({
        location: poli[i],
        stopover: true
      });
  }
//	alert("ここは？");
  calcRoute();
 }



 function calcRoute() {
  var request = {
  origin: poli[0],
  destination: poli[poli.length-1],
  travelMode: google.maps.DirectionsTravelMode.DRIVING,
  unitSystem: google.maps.DirectionsUnitSystem.METRIC,
  waypoints: wayPoints,
  optimizeWaypoints: false,
  avoidHighways: false,
  avoidTolls: false
  };

	//alert("きてる？");
  directionsDisplay.setPanel(document.getElementById('directions-result'));
  directionsService.route(request,
   function(response,status){
   if (status == google.maps.DirectionsStatus.OK){
	//	 alert("最短」毛jロイ");
	//	 alert(response.routes[0].waypoint_order);
	$('.hidden_number').text("");
		 for (var i = 0; i < response.routes[0].legs.length; i++) {
			$("#" + i).text("⬇︎" + Math.floor( response.routes[0].legs[i].duration.value / 60) + "分" + "(" + Math.floor(response.routes[0].legs[i].distance.value / 1000 )+ "Km)" );
		 	};
	//	alert("第一地点と第二地点の距離は" + response.routes[0].legs[0].distance.value / 1000 + "キロメートルあります");
	//	alert("第一地点と第二地点の時間は" + response.routes[0].legs[0].duration.value / 60 + "分かかります");
	//	alert(response.routes[0].legs[1]);
   directionsDisplay.setDirections(response);}
	 alert(status);
   });
 }
</script>