config/routes.rb
Rails.application.routes.draw do
  resources :mypage do
    member do
      get 'top'
    end
  end

  resources :places do
    collection do
      post 'reorder'
    end
  end
  resources :plans do
    collection do
      post 'add'
      post 'add_member'
      post 'datetime'
      get 'modal_restaurant'
    end
    member do
      get 'member'
      get 'confirm'
      get 'pdf'
      get 'finish_mail'
    end
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'top/index'
  resources :blogs
  root 'top#index'

end

app/models/place.rb
class Place < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode

  belongs_to :user
  belongs_to :plan
  has_many :pins, dependent: :destroy

  accepts_nested_attributes_for :pins

  validates :address, presence: true


  #　追加されたplaceをプランの最後の設定する
  def set_route(plan_id)
    max_cnt = Plan.find(plan_id).places.count
    self.route = max_cnt + 1
  end

  #　行きたい度に応じて、⭐️を表示させる。
  #　とりあえず、場所にひもづくピンのなかで、一番目の情報を表示する。
  def show_star
    if self.pins[0].want == 0
      "⭐️"
    elsif self.pins[0].want == 1
      "⭐️⭐️"
    else
      "⭐️⭐️⭐️"
    end
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)
    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    plan_id = Place.find(params[:id]).plan.id
    @place.destroy
    @reorder = Place.where(plan_id: plan_id)
    @reorder.each_with_index {|route, i| Place.update(route, {:route => i + 1})}
    #binding.pry

    #params[:row].each_with_index {|row, i| Place.update(row, {:route => i + 1})}

    respond_to do |format|
      format.html { redirect_to plan_path(plan_id), notice: '削除しました' }
      format.json { head :no_content }
    end
  end

  def reorder
    params[:row].each_with_index {|row, i| Place.update(row, {:route => i + 1})}
    @place = Place.find(params[:row][0])
    @plan = @place.plan
    @places = @plan.places.order(:route)
    i = 1
    @hash = Gmaps4rails.build_markers(@places) do |place, marker|
      marker.lat place.latitude
      marker.lng place.longitude
      marker.infowindow "場所：#{place.address}<br>希望者：#{place.user.name}<br>
                        行きたい度：#{place.show_star}<br>コメント：#{place.pins[0].comment}"
      marker.picture({
                :url    => "/#{i}.png",
                #:url    => "https://graph.facebook.com/#{place.user.uid}/picture?width=32&height=32",
                :width  => "28.00000000001",
                :height => "21.00000000001"
               })
      marker.json({title: place.address})
      i = i + 1
  #    binding.pry
    end

    @point = []
    @hash.each do |hash|
      temp= []
      temp.push(hash[:lat])
      temp.push(hash[:lng])
      @point.push(temp)
    end
  #  render 'redraw'
  #  render :text => "OK"
  @aaa = {hash: @hash, point: @point}
#    binding.pry
    render :json => @aaa

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:user_id, :plan_id, :address, :latitude, :longitude, :route)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :plan_id %><br>
    <%= f.text_field :plan_id %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :route %><br>
    <%= f.number_field :route %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Places</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Plan</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Route</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.user.email %></td>
        <td><%= place.plan.name %></td>
        <td><%= place.address %></td>
        <td><%= place.latitude %></td>
        <td><%= place.longitude %></td>
        <td><%= place.route %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>
<div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</div>
<p>
  <strong>User:</strong>
  <%= @place.user.email %>
</p>

<p>
  <strong>Plan:</strong>
  <%= @place.plan.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @place.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @place.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @place.longitude %>
</p>

<p>
  <strong>Route:</strong>
  <%= @place.route %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>