config/routes.rb
Rails.application.routes.draw do
  resources :mypage do
    member do
      get 'top'
    end
  end

  resources :places do
    collection do
      post 'reorder'
    end
  end
  resources :plans do
    collection do
      post 'add'
      post 'add_member'
      post 'datetime'
      get 'modal_restaurant'
    end
    member do
      get 'member'
      get 'confirm'
      get 'pdf'
      get 'finish_mail'
    end
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'top/index'
  resources :blogs
  root 'top#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tripplan</title>
  <!--<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>-->
  <!--<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>-->
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <!--<%= javascript_include_tag 'markerclusterer_packaged' %>-->
  <%= csrf_meta_tags %>
</head>
<!--<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDqZxCbGeDhg2058AEQnTTmeFJGKQ63Vlk"-->
<!-- type="text/javascript"></script>-->

<!--<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>-->
<!--<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>-->

<!--<script src="//maps.google.com/maps/api/js?v=3.23&key=AIzaSyDqZxCbGeDhg2058AEQnTTmeFJGKQ63Vlk"></script>-->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDqZxCbGeDhg2058AEQnTTmeFJGKQ63Vlk"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>

<body>
    <header>
      <nav class="navbar navbar-default">
      	<div class="container-fluid">
      		<div class="navbar-header">
      			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample2">
      				<span class="sr-only">Toggle navigation</span>
      				<span class="icon-bar"></span>
      				<span class="icon-bar"></span>
      				<span class="icon-bar"></span>
      			</button>
      			<a class="navbar-brand" href="/">
              <%= image_tag 'brandImage.png', size: "20x20" %>
      			</a>
      		</div>

      		<div class="collapse navbar-collapse" id="navbarEexample2">
      			<ul class="nav navbar-nav">
              <% if user_signed_in? %>
                <li role="presentation" class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                  <%= hedder_profile_img(current_user) %> <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li role="presentation"><%= link_to 'プロフィール変更', edit_user_registration_path %></a></li>
                  <li role="presentation"><%= link_to "マイページ", top_mypage_path(current_user) %></a></li>
                  <li role="presentation"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></a></li>
                </ul>
              </li>
                <li><%= link_to "新規プラン作成", new_plan_path, class: 'btn btn-warning', style: "color:black"%></li>
              <% else %>
                <li><%= link_to "サインイン", new_user_registration_path %></li>
                <li><%= link_to "ログイン", new_user_session_path %></li>
              <% end %>
<li>　　</li>

              <li role="presentation" class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                プランを探す <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">

                <li><%= form_for @plan, url: plans_path, method: "get" do |f| %>
                  <div class="field">
                    <%= f.collection_select :area_id, Area.all, :id, :name %>
                  </div>
                  <div class="actions">
                    <%= f.submit class: 'btn btn-primary', value: "検索" %>
                  </div>
                </li>
                <% end %>

              </ul>
              </li>


      			</ul>
      		</div>
      	</div>
      </nav>
    </header>

    <% if notice.present? %>
      <div class = "alert alert-success">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class = "alert alert-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

<%= yield %>

</body>


</html>

app/views/layouts/pdf_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>PdfSample</title>
    <%= wicked_pdf_stylesheet_link_tag "application" -%>
    <%= wicked_pdf_javascript_include_tag "application" %>
  </head>

  <body>

  <%= yield %>

  </body>
</html>

app/views/layouts/plans.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tripplan</title>
  <!--<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>-->
  <!--<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>-->
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <!--<%= javascript_include_tag 'markerclusterer_packaged' %>-->
  <%= csrf_meta_tags %>
</head>
<!--<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDqZxCbGeDhg2058AEQnTTmeFJGKQ63Vlk"-->
<!-- type="text/javascript"></script>-->

<!--<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>-->
<!--<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>-->

<!--<script src="//maps.google.com/maps/api/js?v=3.23&key=AIzaSyDqZxCbGeDhg2058AEQnTTmeFJGKQ63Vlk"></script>-->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDqZxCbGeDhg2058AEQnTTmeFJGKQ63Vlk"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->



<body>
    <header>
      <nav class="navbar navbar-default">
      	<div class="container-fluid">
      		<div class="navbar-header">
      			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample2">
      				<span class="sr-only">Toggle navigation</span>
      				<span class="icon-bar"></span>
      				<span class="icon-bar"></span>
      				<span class="icon-bar"></span>
      			</button>
      			<a class="navbar-brand" href="/">

              <%= image_tag 'brandImage.png', size: "20x20" %>
      			</a>
      		</div>

      		<div class="collapse navbar-collapse" id="navbarEexample2">
      			<ul class="nav navbar-nav">
              <% if user_signed_in? %>
              <li role="presentation" class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                <%= hedder_profile_img(current_user) %> <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li role="presentation"><%= link_to 'プロフィール変更', edit_user_registration_path %></a></li>
                <li role="presentation"><%= link_to "マイページ", top_mypage_path(current_user) %></a></li>
                <li role="presentation"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></a></li>
              </ul>
              </li>

              <% unless @plan.nil? %>
                <% unless @plan.id.nil? %>

                  <li role="presentation" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                      <%= @plan.name %> <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                      <input type="hidden" id ="plan_id" name="plan_id" value="<%= @plan.id %>"></input>
                      <li role="presentation"><b>エリア：<%= @plan.area.name %></b></li>
                      <li role="presentation"><b>日程：</b></li>
                      <li role="presentation"><b id = "min"><%= @plan.start_date %></b>-<b><%= @plan.end_date %></b></li>
                      <div id="max" class = "<%= @plan.end_date.tomorrow %>"></div>
                      <% if @members.ids.include?(current_user.id) %>
                        <br>
                        <li role="presentation"><%= button_to '基本情報を編集する', edit_plan_path(@plan), method: "get", class: "btn btn-info" %></li>
                      <% end %>
                    </ul>
                  </li>
                      <% unless @members.nil? %>
                  <li role="presentation" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                    メンバー <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" role="menu">
                    <li role="presentation">

                      <% @members.each do |member| %>
                        <td>
                          <%=link_to member.name, top_mypage_path(member)%>
                        </td>
                        <br>
                      	<%= profile_img(member) %>
                      <% end %>
                      <% if @members.ids.include?(current_user.id) %>
                        <br>
                        <td><%= button_to 'メンバーを追加する', member_plan_path(@plan), method: "get", class: "btn btn-info" %></td>
                        <br>
                      <% end %>


                    </li>
                  </ul>
                  </li>
<% end %>
                <% end %>
              <% end %>

              <% else %>
                <li><%= link_to "サインイン", new_user_registration_path %></li>
                <li><%= link_to "ログイン", new_user_session_path %></li>

              <% end %>

      			</ul>
      		</div>
      	</div>
      </nav>
    </header>

    <% if notice.present? %>
      <div class = "alert alert-success">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class = "alert alert-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

<%= yield %>

</body>


</html>